nome = str(input('Digite seu nome completo: ')).strip()
print('Analizando seu nome...')
print(f'Seu nome em maiusculas é {nome}'.upper())
print(f'Seu nome em minusculas é {nome}'.lower())
print(f'Seu nome tem ao todo {len(nome)} letras')
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras')